### PR TITLE
Automate OB withdrawals

### PR DESCRIPTION
**Pull request by Gauthamastro**
## Describe your changes

Automate Ob withdrawals to a safe limit, then make it claimable

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] I removed all Clippy and Formatting Warnings. 
- [x] I added required Copyrights.

### CODE REVIEW

**Comment by zktony** [comment]
Hey @serhii-temchenko, could you please regen weights for OCEX Pallet?

**Comment by serhii-temchenko** [comment]
> Hey @serhii-temchenko, could you please regen weights for OCEX Pallet?

Hi @zktony. weights were updated, please take a look.

**Review by serhii-temchenko — CHANGES_REQUESTED** [review]
Please fix CI errors.

**Comment by Gauthamastro** [comment]
> Please fix CI errors.

Tested locally and checks pass, merging.

**Pull request merged**
