### PR TITLE
Update run-a-validator.md

### PR DESCRIPTION
**Pull request by zktony**
Updated version run-a-validator.md

### CODE REVIEW

**Comment by jaymansfield** [comment]
Why not just use latest rather then hard coding to v4.0.0? More likely to stay up to date that way.

https://github.com/Polkadex-Substrate/Polkadex/releases/download/latest/PolkadexNodeUbuntu.zip

**Comment by zktony** [comment]
> Why not just use latest rather then hard coding to v4.0.0? More likely to stay up to date that way.
> 
> https://github.com/Polkadex-Substrate/Polkadex/releases/download/latest/PolkadexNodeUbuntu.zip

sounds good

**Review by pavankanteti — APPROVED** [review]

**Review by serhii-temchenko — CHANGES_REQUESTED** [review]
To make it `latest` - we have to change release process which will affect github workflow and artifacts creation... do we want that? because with just this change we have documentation with broken command since this link will return `404`...

**Comment by jaymansfield** [comment]
latest should be supported by default on github.

link correction: https://github.com/Polkadex-Substrate/Polkadex/releases/latest/download/PolkadexNodeUbuntu.zip

**Comment by serhii-temchenko** [comment]
> latest should be supported by default on github.
> 
> link correction: https://github.com/Polkadex-Substrate/Polkadex/releases/latest/download/PolkadexNodeUbuntu.zip

Ok, thanks, checked [github docs](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases)... 
@zktony please update link to `https://github.com/Polkadex-Substrate/Polkadex/releases/latest/download/PolkadexNodeUbuntu.zip`

**Pull request merged**
