### PR TITLE
Fixed node build in docker

### PR DESCRIPTION
**Pull request by serhii-temchenko**
In this PR was corrected dockerfile with a proper release build. Had issue with building node due dependency conflict.

This PR will close issue #567.

### CODE REVIEW

**Comment by felixfaisal** [comment]
Hey @serhii-temchenko I wanted to confirm if you are able to run the image which is built from this dockerfile.

**Comment by serhii-temchenko** [comment]
> Hey @serhii-temchenko I wanted to confirm if you are able to run the image which is built from this dockerfile.

Yes, node is running properly.

**Comment by felixfaisal** [comment]
LGTM ✅

**Review by felixfaisal — APPROVED** [review]

**Review by 35359595 — APPROVED** [review]
Builds just fine for me

**Pull request merged**
