### PR TITLE
Issue/reserve balance

### LINKED ISSUE #22: Balance transfers are messed up!!
I am not getting the expected Free balance in tests after placing BidLimit orders that consume more than 1  price level.  The state of the order book is correct, but the balance results are not correct

### PR DESCRIPTION
**Pull request by ksr30**
Fixed #22

### CODE REVIEW

**Comment by ksr30** [comment]
@Gauthamastro please have a look

**Comment by Gauthamastro** [comment]
@visiondream3  Please check and let me know.

**Comment by visiondream3** [comment]
ok 👍

**Review by Gauthamastro — APPROVED** [review]
Problem is solved

**Pull request merged**
