### PR TITLE
Error Msg Changed

### PR DESCRIPTION
**Pull request by nakul1010**
Changed error message to MinterIsNotValid instead of MinterMustBeRelayer

### CODE REVIEW

**Review by serhii-temchenko — CHANGES_REQUESTED** [review]
Please add tests to cover this.

**Comment by nakul1010** [comment]
> MinterMustBeRelayer

Test case already present [here](https://github.com/Polkadex-Substrate/Polkadex/blob/e46ee3a44c36cd6387a5da0b21e7a01a532ed133/pallets/asset-handler/src/tests.rs#L131)

**Comment by serhii-temchenko** [comment]
> > MinterMustBeRelayer
> 
> Test case already present [here](https://github.com/Polkadex-Substrate/Polkadex/blob/e46ee3a44c36cd6387a5da0b21e7a01a532ed133/pallets/asset-handler/src/tests.rs#L131)

Oh ye. Missed that. Thanks.

**Review by serhii-temchenko — APPROVED** [review]

**Comment by serhii-temchenko** [comment]
Please merge only if CI is passed.

**Review by Gauthamastro — APPROVED** [review]

**Pull request merged**
